(node:2643800) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Started with the following options:
{
  debug: true,
  mitmIp: '10.0.3.1',
  autoAccess: true,
  autoAccessCache: 5000,
  maxAttemptsPerConnection: 6,
  sshServerIdentifier: 'SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2',
  containerMountPathPrefix: '/var/lib/lxc',
  containerMountPathSuffix: 'rootfs/',
  loggingAttackerStreams: '/home/student/MITM/logs/session_streams',
  loggingAuthenticationAttempts: '/home/student/MITM/logs/authentication_attempts',
  loggingLogins: '/home/student/MITM/logs/logins',
  loggingLogouts: '/home/student/MITM/logs/logouts',
  loggingKeystrokes: '/home/student/MITM/logs/keystrokes',
  containerName: 'nobanner-nosession-40413',
  containerIp: '10.0.3.33',
  mitmPort: 40413,
  autoAccessFixed: 1
}
2024-11-06 03:15:20.131 - [Info] MITM Version: 2
2024-11-06 03:15:20.134 - [Info] Auto Access Enabled: true
2024-11-06 03:15:20.134 - [Debug] [Init] Auto Access Theshold Achieved: false
2024-11-06 03:15:20.156 - [Info] SSH man-in-the-middle server for 10.0.3.33 listening on 10.0.3.1:40413
2024-11-06 03:16:02.108 - [Debug] [Connection] Attacker connected: 185.129.119.33 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-06 03:16:03.298 - [Debug] [Auth] Attacker 185.129.119.33 trying to authenticate with 'password'
2024-11-06 03:16:03.299 - [Debug] [Auto Access] Attacker: 185.129.119.33, Threshold: 1, Attempts: 1
2024-11-06 03:16:03.300 - [Debug] [Auto Access] Compromising the honeypot
2024-11-06 03:16:03.300 - [Debug] [Auto Access] Adding the following credentials: 'zj:123'
2024-11-06 03:16:03.632 - [Debug] [Auto Access] Auto-access is now disabled for the remainder of this MITM server instance
2024-11-06 03:16:03.634 - [Debug] [Auth] Valid credentials - Password Authentication
2024-11-06 03:16:03.634 - [Debug] [LXC] Attempting to connect to the honeypot: 10.0.3.33
2024-11-06 03:16:03.732 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2024-11-06 03:16:04.572 - [Debug] [EXEC] Noninteractive mode attacker command: cd ~; chattr -ia .ssh; lockr -ia .ssh
2024-11-06 03:16:05.835 - [Debug] [Connection] Attacker connected: 185.129.119.33 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-06 03:16:07.127 - [Debug] [Auth] Attacker 185.129.119.33 trying to authenticate with 'password'
2024-11-06 03:16:07.128 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2024-11-06 03:16:07.129 - [Debug] [Auth] Attacker: 185.129.119.33 has so far made 1 attempts. Remaining: 5 attempts
2024-11-06 03:16:07.582 - [Debug] [Connection] Attacker closed the connection
2024-11-06 03:16:07.788 - [Debug] [Connection] Attacker connected: 185.129.119.33 | Client Identification: SSH-2.0-libssh_0.9.6
2024-11-06 03:16:09.037 - [Debug] [Auth] Attacker 185.129.119.33 trying to authenticate with 'password'
2024-11-06 03:16:09.038 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2024-11-06 03:16:09.038 - [Debug] [Auth] Attacker: 185.129.119.33 has so far made 1 attempts. Remaining: 5 attempts
{"level":"error","message":"Forever detected script was killed by signal: SIGKILL"}
